# Practice Dry Code Exercise
* **Author:** Rick Forest  
* **Date:** 10/7/2021 

## Packages

In [1]:
import os
from glob import glob

import matplotlib.pyplot as plt
import seaborn as sns

import numpy as np
import pandas as pd
import earthpy as et

## Directories

In [2]:
home_dir = et.io.HOME
work_dir = os.path.join(home_dir, 'earth-analytics', 'earth-analytics-homework')
data_dir = os.path.join(home_dir, 'earth-analytics', 'data', 'earthpy-downloads')

os.chdir(work_dir)
os.getcwd()

'C:\\Users\\rick\\earth-analytics\\earth-analytics-homework'

## Download data

### *numpy*

In [3]:
file_url = "https://ndownloader.figshare.com/files/12807380"
data_path = et.data.get_data(url=file_url)
file_name = os.path.basename(os.path.normpath(data_path))
file_name

'monthly-precip-1988-to-1992.csv'

In [4]:
# first check downloaded file for delimiters and numbers versus text
if os.path.exists(data_path):
    monthly_precip_1988_to_1992 = np.loadtxt(data_path, delimiter=",")
monthly_precip_1988_to_1992

array([[0.4 , 1.14, 2.53, 1.48, 3.7 , 0.7 , 0.71, 1.33, 2.02, 0.03, 0.75,
        2.16],
       [1.19, 1.27, 0.97, 1.95, 2.68, 2.93, 1.43, 1.63, 3.54, 1.4 , 0.09,
        1.54],
       [1.04, 1.32, 4.55, 2.16, 1.73, 0.39, 4.23, 1.13, 1.84, 0.96, 1.6 ,
        0.75],
       [1.05, 0.15, 0.43, 2.41, 2.9 , 3.59, 3.11, 2.08, 1.21, 0.93, 3.3 ,
        0.01],
       [0.67, 0.  , 5.17, 0.46, 1.7 , 0.96, 1.13, 3.08, 0.02, 0.79, 2.56,
        0.84]])

In [5]:
file_url = "https://ndownloader.figshare.com/files/12807383"
data_path = et.data.get_data(url=file_url)
file_name = os.path.basename(os.path.normpath(data_path))
file_name

'monthly-precip-1993-to-1997.csv'

In [6]:
if os.path.exists(data_path):
    monthly_precip_1993_to_1997 = np.loadtxt(data_path, delimiter=",")
monthly_precip_1993_to_1997

array([[0.25, 0.9 , 2.15, 2.56, 1.73, 3.38, 1.4 , 1.04, 3.32, 2.42, 2.17,
        0.55],
       [0.86, 1.37, 1.61, 3.46, 1.35, 0.93, 0.35, 2.56, 0.54, 1.02, 2.25,
        0.49],
       [0.64, 1.53, 1.21, 5.45, 9.59, 4.03, 0.72, 1.45, 2.96, 0.59, 1.51,
        0.25],
       [1.89, 0.29, 2.16, 1.49, 4.63, 2.77, 1.96, 0.63, 3.48, 0.28, 1.43,
        0.37],
       [0.87, 1.83, 0.91, 5.77, 2.19, 3.69, 1.14, 5.27, 1.92, 2.7 , 1.52,
        0.68]])

### *pandas*

In [7]:
file_url = "https://ndownloader.figshare.com/files/12807389"
data_path = et.data.get_data(url=file_url)

file_name = os.path.basename(os.path.normpath(data_path))
file_name

'temp-1991-to-1995-months.csv'

In [8]:
temp_1991_to_1995_months = pd.read_csv(data_path)
temp_1991_to_1995_months

Year  January  February  March  April   May  June  July  August  September  \
0  1991     29.9      40.9   42.8   47.8  58.2  66.6  70.5    69.2       61.7   
1  1992     35.9      40.6   43.3   54.3  59.1  62.9  68.3    66.3       64.4   
2  1993     28.3      30.6   42.4   47.6  57.5  64.5  69.5    67.3       58.8   
3  1994     35.5      31.9   43.9   47.6  60.8  70.0  71.2    70.9       65.0   
4  1995     34.5      38.3   42.1   45.1  50.9  62.4  70.5    74.0       60.4   

   October  November  December  
0     52.1      36.8      35.3  
1     54.1      34.1      29.2  
2     48.7      35.6      35.4  
3     50.6      36.6      36.1  
4     50.5      45.0      36.3

In [9]:
file_url = "https://ndownloader.figshare.com/files/12807386"
data_path = et.data.get_data(url=file_url)

file_name = os.path.basename(os.path.normpath(data_path))
file_name

'temp-1996-to-2000-months.csv'

In [10]:
temp_1996_to_2000_months = pd.read_csv(data_path)
temp_1996_to_2000_months

Year  January  February  March  April   May  June  July  August  September  \
0  1996     29.7      37.7   37.9   50.4  58.9  66.9  71.5    69.5       60.8   
1  1997     31.3      32.8   45.5   42.8  57.4  66.5  71.4    68.7       64.0   
2  1998     36.5      36.4   38.7   46.5  58.8  62.1  72.8    70.7       67.1   
3  1999     36.4      42.1   46.0   44.5  55.6  64.8  73.5    69.3       58.5   
4  2000     36.4      41.0   42.9   51.2  61.0  67.4  74.7    73.0       63.1   

   October  November  December  
0     53.1      40.6      36.5  
1     52.7      37.9      33.9  
2     50.4      44.0      32.2  
3     51.9      48.0      36.9  
4     49.6      31.4      31.2

## Question 1

Select the second row of data (including all columns) from the numpy array containing the data for 1988 to 1992, and save to a new numpy array.

In [11]:
monthly_precip_1988_to_1992

array([[0.4 , 1.14, 2.53, 1.48, 3.7 , 0.7 , 0.71, 1.33, 2.02, 0.03, 0.75,
        2.16],
       [1.19, 1.27, 0.97, 1.95, 2.68, 2.93, 1.43, 1.63, 3.54, 1.4 , 0.09,
        1.54],
       [1.04, 1.32, 4.55, 2.16, 1.73, 0.39, 4.23, 1.13, 1.84, 0.96, 1.6 ,
        0.75],
       [1.05, 0.15, 0.43, 2.41, 2.9 , 3.59, 3.11, 2.08, 1.21, 0.93, 3.3 ,
        0.01],
       [0.67, 0.  , 5.17, 0.46, 1.7 , 0.96, 1.13, 3.08, 0.02, 0.79, 2.56,
        0.84]])

In [12]:
monthly_precip_1989 = monthly_precip_1988_to_1992[1,]
monthly_precip_1989 

array([1.19, 1.27, 0.97, 1.95, 2.68, 2.93, 1.43, 1.63, 3.54, 1.4 , 0.09,
       1.54])

## Question 2

Write a conditional statement that checks whether the numpy array created in the previous question (i.e. the selection) is a one-dimensional numpy array.

Print a message stating whether or not the array is one-dimensional.

In [13]:
if monthly_precip_1989.ndim == 1:
    print("Array is one=dimensional")
else:
    print("Array is NOT one=dimensional")

Array is one=dimensional


## Question 3

Modify your conditional statement from the previous question, so that your if and else statements execute different code, not just printing messages.

For the if statement, rather than printing a message, print the shape of the numpy array from the previous question (i.e. the selection).

For the else statement, rather than printing a message, include the following code lines to be executed (i.e. if the array is not one-dimensional):

arrayname_1d = arrayname.flatten()  
print(arrayname_1d.shape)  

These code lines will flatten a numpy array (in this case named arrayname) to a one-dimensional array, save it to a new array called arrayname_1d, and print the shape of the new array.

In [14]:
if monthly_precip_1989.ndim == 1:
    print('dimensions = 1')
    print(monthly_precip_1989.shape)
else:
    monthly_precip_1989_1d = monthly_precip_1989.flatten()
    print('dimensions not equal 1: flatten')
    print(monthly_precip_1989_1d.shape)

dimensions = 1
(12,)


## Question 4

Manually create a one-dimensional numpy array that contains the month names (i.e. January to December).  

Write a conditional statement to check that this new array for month names has the same shape as the numpy array from the previous question (i.e. the selection).  

Print a message stating whether are not these arrays have the same shape and can be plotted together.

In [15]:
month_names = np.array(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August',
 'September', 'October', 'November', 'December'])
month_names

array(['January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype='<U9')

In [16]:
if monthly_precip_1989.shape == month_names.shape:
    print("Arrays are the same shape and can be plotted together.")
else:
    print("Arrays are NOT same shape")

Arrays are the same shape and can be plotted together.


## Question 5

If the arrays are the same shape:  plot  
else if the flattened first array and flattened second array are the same shape:  plot flattened arrays  
else do NOT plot and print warning message

## Question 6

Write a loop to run the info() method on the two pandas dataframes that you imported in this activity, and print the results.



In [17]:
data_frame_list = []
data_frame_list.append(temp_1991_to_1995_months)
data_frame_list.append(temp_1996_to_2000_months)

for i in range(len(data_frame_list)):
    data_frame_list[i].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Year       5 non-null      int64  
 1   January    5 non-null      float64
 2   February   5 non-null      float64
 3   March      5 non-null      float64
 4   April      5 non-null      float64
 5   May        5 non-null      float64
 6   June       5 non-null      float64
 7   July       5 non-null      float64
 8   August     5 non-null      float64
 9   September  5 non-null      float64
 10  October    5 non-null      float64
 11  November   5 non-null      float64
 12  December   5 non-null      float64
dtypes: float64(12), int64(1)
memory usage: 648.0 bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Year       5 non-null      int64  
 1   January    5 non-

## Question 7

Write a loop to run the .describe() method on each column in the pandas dataframe containing the data for 1996 to 2000).

In [25]:
df_columns = list(temp_1996_to_2000_months.columns)
df_columns

['Year',
 'January',
 'February',
 'March',
 'April',
 'May',
 'June',
 'July',
 'August',
 'September',
 'October',
 'November',
 'December']

In [26]:
df_month_columns = df_columns[1:]
df_month_columns

['January',
 'February',
 'March',
 'April',
 'May',
 'June',
 'July',
 'August',
 'September',
 'October',
 'November',
 'December']

In [27]:
for i in range(len(df_month_columns)):
    print(temp_1996_to_2000_months[[df_month_columns[i]]].describe())

         January
count   5.000000
mean   34.060000
std     3.298939
min    29.700000
25%    31.300000
50%    36.400000
75%    36.400000
max    36.500000
        February
count   5.000000
mean   38.000000
std     3.724916
min    32.800000
25%    36.400000
50%    37.700000
75%    41.000000
max    42.100000
           March
count   5.000000
mean   42.200000
std     3.760319
min    37.900000
25%    38.700000
50%    42.900000
75%    45.500000
max    46.000000
           April
count   5.000000
mean   47.080000
std     3.650616
min    42.800000
25%    44.500000
50%    46.500000
75%    50.400000
max    51.200000
           May
count   5.0000
mean   58.3400
std     1.9995
min    55.6000
25%    57.4000
50%    58.8000
75%    58.9000
max    61.0000
            June
count   5.000000
mean   65.540000
std     2.157081
min    62.100000
25%    64.800000
50%    66.500000
75%    66.900000
max    67.400000
            July
count   5.000000
mean   72.780000
std     1.391761
min    71.400000
25%    71.50000

## Question 8

Write a function that calculates the mean across columns of a numpy array.

In [28]:
def array_mean(array):
    """
    Calcualate column averages in numpy array. 
    
    Parameters
    ----------
    array : array of numbers

    Returns
    ------
    array_col_avg : one-dimensional numpy array of column averages

    """
    array_col_avg = np.mean(array, axis=0) 
    
    return array_col_avg

## Question 9

Run the function created in the previous question (i.e. to calculate mean of columns in a numpy array) on the numpy array containing data for 1993 to 1997. Save the output to a new numpy array.

In [29]:
monthly_mean_precip_1993_to_1997 = array_mean(monthly_precip_1993_to_1997)
monthly_mean_precip_1993_to_1997

array([0.902, 1.184, 1.608, 3.746, 3.898, 2.96 , 1.114, 2.19 , 2.444,
       1.402, 1.776, 0.468])

## Question 10

Write a sentence or two on what you would need to know how to do, in order to save the output from a function that is running on multiple arrays in a loop.

1. Create an input array list that contains the multiple numpy arrays to process, and an empty output array list to hold the averaged values. 
2. Execute a for loop that calls a function to calculate the mean of the values and append the results to the output array list.

In [30]:
input_array_list = list([monthly_precip_1988_to_1992,monthly_precip_1993_to_1997])
output_array_list = []

for i in range(len(input_array_list)):
    output_array_list.append(array_mean(input_array_list[i]))
output_array_list

[array([0.87 , 0.776, 2.73 , 1.692, 2.542, 1.714, 2.122, 1.85 , 1.726,
        0.822, 1.66 , 1.06 ]),
 array([0.902, 1.184, 1.608, 3.746, 3.898, 2.96 , 1.114, 2.19 , 2.444,
        1.402, 1.776, 0.468])]